# Gradle Options
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false

# Project
mod_version=26.1-r1.6
project_group=net.rebel459.end_reborn
license=Legacy License
java_version=25

# Mod
mod_author=Rebel459
mod_id=end_reborn
mod_name=End Reborn
mod_description=A lightweight, vanilla-style expansion of Minecraft's lategame and End dimension content.

# Minecraft
minecraft_version=26.1.2
neo_form_version=26.1.2-1

# Fabric
fabric_loader=0.19.3
fabric_api=0.155.2+26.1.2
fabric_minecraft_version=>=26.1 <26.2

# NeoForge
neoforge_version=26.1.2.94
neoforge_minecraft_version=[26.1, 26.2)

# Common Dependencies
unified_version=26.1-r5.3
cloth_version=26.1.154
patcher_version=2.1-mc26.1

# Fabric Dependencies
modmenu_version=18.0.0-alpha.8
fd_version=26.1-3.5.2